[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/asset_registry",
  "programs/data_registry",
  "programs/identity_registry",
  "programs/policy_registry",
]