[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "asset_controller",
  "data_registry",
  "identity_registry",
  "policy_engine",
]

[programs.localnet]
asset_controller = "DtrBDukceZpUnWmeNzqtoBQPdXW8p9xmWYG1z7qMt8qG"
data_registry = "8WRaNVNMDqdwADbKYj7fBd47i2e5SFMSEs8TrA2Vd5io"
identity_registry = "qDnvwpjBYjH1vs1N1CSdbVkEkePp2acL7TphAYZDeoV"
policy_engine = "6FcM5R2KcdUGcdLunzLm3XLRFr7FiF6Hdz3EWni8YPa2"

[scripts]
test = "cd ../clients/rwa-sdk && yarn test"


[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
