[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "asset_controller",
  "data_registry",
  "identity_registry",
  "policy_engine",
]

[programs.localnet]
asset_controller = "acpcFrzEYKjVLvZGWueTV8vyDjhu3oKC7sN38QELLan"
data_registry = "dataeP5X1e7XsWN1ovDSEDP5cqaEUnKBmHE5iZhXPVw"
identity_registry = "idtynCMYbdisCTv4FrCWPSQboZb1uM4TV2cPi79yxQf"
policy_engine = "po1cPf1eyUJJPqULw4so3T4JU9pdFn83CDyuLEKFAau"

[scripts]
test = "cd ../clients/rwa-token-sdk && yarn test"


[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
