name: build
env:
  cli-id: anchor-v0.29.2-solana-1.17.0
on:
  pull_request:
    branches:
      - 'main'
jobs:
  build-cli-deps:
    runs-on: ubicloud-standard-8
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
      - id: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - id: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

  tests:
    runs-on: ubicloud-standard-8
    needs: [build-cli-deps]
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
      - id: install-os-deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: cd clients/rwa-sdk && yarn install
      - run: cd programs && cargo fmt -- --check
      - run: cd programs && cargo clippy -- -D warnings
      - run: cd programs && ./anchor build
      - run: cd programs && ./anchor test