name: tests
env:
  cli-id: anchor-v0.30.0-solana-1.18.8
on:
  pull_request:
    branches:
      - 'staging'
jobs:
  setup-tests:
    runs-on: ubicloud-standard-16
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
      - id: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - id: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.18.8/install)"

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

      - id: install-anchor-cli
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked

  run-tests:
    runs-on: ubicloud-standard-16
    needs: [setup-tests]
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo/bin/anchor
      - id: install-os-deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: cd clients/rwa-token-sdk && yarn install
      - run: cd clients/rwa-token-sdk && yarn lint
      - run: solana-keygen new --no-bip39-passphrase
      - run: cd programs && cargo fmt -- --check
      - run: cd programs && cargo clippy -- -D warnings
      - run: cd programs && anchor build
      - run: cd programs && anchor test